#!/bin/bash

# convert tag to BUILD_TYPE
BUILD_TYPE=Release
if [ "$SOURCE_BRANCH" == "dbg" ]; then
  BUILD_TYPE=Debug
fi

# $IMAGE_NAME var is injected into the build so the tag is correct.
# $DOCKERFILE_PATH var is injected into the build so the path to the Dockerfile is correct.
echo "docker build -f $DOCKERFILE_PATH --build-arg BUILD_TYPE=$BUILD_TYPE -t $IMAGE_NAME ."
docker build -f $DOCKERFILE_PATH --build-arg BUILD_TYPE=$BUILD_TYPE -t $IMAGE_NAME .
